--Q1. Total revenue generated by male vs female customers?
SELECT gender,SUM("purchase_amount_(usd)") AS toal_revenue
FROM customer
GROUP BY gender;

--Q2. Find Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, "purchase_amount_(usd)" 
FROM customer 
WHERE LOWER (discount_applied) = 'yes'
AND  "purchase_amount_(usd)" > (SELECT AVG ("purchase_amount_(usd)")
 FROM customer
);

-- Q3. Find the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND (AVG(review_rating::numeric), 3) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4. Find the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG("purchase_amount_(usd)"), 2) AS avg_purchase_amount
FROM customer 
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT subscription_status, ROUND(AVG("purchase_amount_(usd)"), 2) AS average_spend,
SUM("purchase_amount_(usd)") AS total_revenue, 
COUNT(*) AS total_transactions
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, COUNT(*) AS total_purchases,
COUNT (CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discounted_purchases, ROUND(100.0* 
COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'ELSE 'Loyal'
END AS customer_segment
FROM customer )
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 5 most purchased products within each category? 
WITH ranked_products AS ( SELECT category, item_purchased, COUNT(*) AS total_purchased,
DENSE_RANK() OVER (PARTITION BY category 
ORDER BY COUNT(*) DESC ) AS product_rank
FROM customer
GROUP BY category, item_purchased )
SELECT category, item_purchased, total_purchased
FROM ranked_products
WHERE product_rank <= 5
ORDER BY category, product_rank;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers 
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. Compare the subscribe rates of repeat buyers directly against non-repeat buyers?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5 Purchases)'
        ELSE 'Regular Buyer (<=5 Purchases)'
    END AS buyer_category,subscription_status,
    COUNT(*) AS total_customers,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (
            PARTITION BY CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5 Purchases)' ELSE 'Regular Buyer (<=5 Purchases)' END
        ), 2
    ) AS percentage_within_group
FROM customer
GROUP BY buyer_category, subscription_status
ORDER BY buyer_category, subscription_status DESC;

--Q11. What is the revenue contribution of each age group? 
SELECT 
CASE 
   WHEN age < 25 THEN 'Under 25'
   WHEN age BETWEEN 25 AND 40 THEN '25-40' 
   WHEN age BETWEEN 41 AND 60 THEN '41-60'
   ELSE '60+'
END AS age_group,
SUM("purchase_amount_(usd)") AS total_revenue,ROUND(100.0 * SUM("purchase_amount_(usd)") / SUM(SUM("purchase_amount_(usd)")) OVER (), 2) AS revenue_percentage
FROM customer
GROUP BY 1
ORDER BY total_revenue DESC;
